version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:1.28.0
    container_name: vaultwarden
    volumes:
      - /home/username/vaultwarden/data/:/data/
    networks:
      - traefik_default
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_default
      # Redirect to get the certs
      - traefik.http.middlewares.redirect-https.redirectScheme.scheme=https
      - traefik.http.middlewares.redirect-https.redirectScheme.permanent=true
      # routers & services
      - traefik.http.routers.vaultwarden-ui-https.rule=Host(`vaultwarden.local.example.com`)
      - traefik.http.routers.vaultwarden-ui-https.entrypoints=websecure
      - traefik.http.routers.vaultwarden-ui-https.tls=true
      - traefik.http.routers.vaultwarden-ui-https.service=vaultwarden-ui
      - traefik.http.routers.vaultwarden-ui-http.rule=Host(`vaultwarden.local.example.com`)
      - traefik.http.routers.vaultwarden-ui-http.entrypoints=web
      - traefik.http.routers.vaultwarden-ui-http.middlewares=redirect-https
      - traefik.http.routers.vaultwarden-ui-http.service=vaultwarden-ui
      - traefik.http.services.vaultwarden-ui.loadbalancer.server.port=80
      - traefik.http.routers.vaultwarden-websocket-https.rule=Host(`vaultwarden.local.example.com`) && Path(`/#/login`)
      - traefik.http.routers.vaultwarden-websocket-https.entrypoints=websecure
      - traefik.http.routers.vaultwarden-websocket-https.tls=true
      - traefik.http.routers.vaultwarden-websocket-https.service=vaultwarden-websocket
      - traefik.http.routers.vaultwarden-websocket-http.rule=Host(`vaultwarden.local.example.com`) && Path(`/#/login`)
      - traefik.http.routers.vaultwarden-websocket-http.entrypoints=web
      - traefik.http.routers.vaultwarden-websocket-http.middlewares=redirect-https
      - traefik.http.routers.vaultwarden-websocket-http.service=vaultwarden-websocket
      - traefik.http.services.vaultwarden-websocket.loadbalancer.server.port=3012

networks:
  traefik_default:
    external: true
